.TH "Movian" 1
.SH NAME
movian \ - OpenGL based mediaplayer
.SH SYNOPSIS
.B movian
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B Movian
is an OpenGL based mediaplayer.
All setup and configuration of Movian is done from within the program itself.
.SH OPTIONS
All arguments are optional.
.TP
\fB\-s \fR\fIpath\fR
Store settings in \fR\fIpath\fR. Default is to store settings in
$HOME/.hts/movian
.SH "AUTHOR"
.B Movian
and this man page is maintained by Andreas Oeman
.PP
(andreas a lonelycoder d com)
.PP
You may also visit #hts at irc.freenode.net
.SH "SEE ALSO"
.BR https://movian.tv
