.TH "Showtime" 1
.SH NAME
showtime \ - OpenGL based mediaplayer
.SH SYNOPSIS
.B showtime
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B Showtime
is an OpenGL based mediaplayer.
All setup and configuration of Showtime is done from within the program itself.
.SH OPTIONS
All arguments are optional.
.TP
\fB\-s \fR\fIpath\fR
Store settings in \fR\fIpath\fR. Default is to store settings in
$HOME/.hts/showtime
.SH "AUTHOR"
.B Showtime
and this man page is maintained by Andreas Oeman
.PP
(andreas a lonelycoder d com)
.PP
You may also visit #hts at irc.freenode.net
.SH "SEE ALSO"
.BR http://hts.lonelycoder.com/
