#!/bin/sh

if [ $# != 4 ]; then
  echo "Usage: $0 srcdir volname iconfile dmgfile"
  exit
fi

SRCDIR=$1
VOLNAME=$2
ICONFILE=$3
DMGFILE=$4

rm -f $DMGFILE
hdiutil create -format UDRW -volname $VOLNAME -srcfolder $SRCDIR $DMGFILE
mkdir tmpmnt
hdiutil attach $DMGFILE -readwrite -mountroot tmpmnt
ln -s /Applications tmpmnt/$VOLNAME/Applications
cp $ICONFILE tmpmnt/$VOLNAME/.VolumeIcon.icns
/Developer/Tools/SetFile -a C tmpmnt/$VOLNAME/.VolumeIcon.icns tmpmnt/$VOLNAME
hdiutil detach tmpmnt/$VOLNAME
rmdir tmpmnt
mv $DMGFILE $DMGFILE.UDRW
hdiutil convert $DMGFILE.UDRW -format UDBZ -o $DMGFILE
rm $DMGFILE.UDRW