#!/bin/bash
set -e
set -u

PARALLEL=-j6

TOPDIR=${PWD}
PS3SUPPORT=${PWD}/ps3support

export FFMPEG=${PS3SUPPORT}/ffmpeg

mkdir -p ${FFMPEG}

if [ ! -e ${FFMPEG}/include/libavcodec/avcodec.h ] || [[ $# == 1 && $1 == -u ]] ; then
    cd ${FFMPEG}
    if ! test -e src/.git ; then
        git clone git://github.com/andoma/libav.git src
    else
        cd ${FFMPEG}/src
        git pull
        cd ${FFMPEG}
    fi

    echo Configuring FFmpeg...

    src/configure \
        --disable-encoders \
        --disable-bsfs \
        --disable-filters \
        --disable-muxers \
        --disable-devices \
        --disable-protocols \
        --disable-network \
        --disable-shared \
        --enable-static \
        --prefix=${PS3SUPPORT}/ffmpeg \
	--extra-cflags="-I${PSL1GHT}/ppu/include -I${PSL1GHT}/ppu/include/simdmath -mhard-float -fmodulo-sched -ffunction-sections -fdata-sections -include ${TOPDIR}/support/nostrictansi.h" \
	--extra-ldflags="-L${PSL1GHT}/ppu/lib -lrt -llv2" \
        --disable-ffserver \
        --disable-ffmpeg \
        --disable-ffplay \
        --disable-ffprobe \
        --disable-bzlib \
	--cross-prefix=ppu- \
	--enable-cross-compile \
	--arch=powerpc64 \
    --cpu=cell \
	--target-os=none \
	--disable-decoder=twinvq \
	--disable-decoder=snow \
	--disable-decoder=cavs

    make ${PARALLEL}
    make install

else
    echo "Nothing to do, use -u to update"
fi
