#!/bin/bash
set -e
set -u

PARALLEL=-j6

TOPDIR=${PWD}
PS3SUPPORT=${PWD}/ps3support

export FFMPEG=${PS3SUPPORT}/ffmpeg

mkdir -p ${FFMPEG}

if ! test -e ${FFMPEG}/include/libavcodec/avcodec.h ; then
    cd ${FFMPEG}
    git clone git://github.com/andoma/libav.git src
    echo Configuring FFmpeg...

    src/configure \
        --disable-encoders \
        --disable-bsfs \
        --disable-filters \
        --disable-muxers \
        --disable-devices \
        --disable-protocols \
        --disable-network \
        --disable-stripping \
        --disable-static \
        --disable-shared \
        --enable-static \
        --prefix=${PS3SUPPORT}/ffmpeg \
	--extra-cflags="-mminimal-toc -B${PSL1GHT}/target/lib -B${PS3DEV}/host/ppu/lib -I${PS3DEV}/host/ppu/include -include ${TOPDIR}/support/nostrictansi.h" \
	--extra-ldflags="-L${PS3DEV}/host/ppu/lib -B${PSL1GHT}/target/lib -B${PS3DEV}/host/ppu/lib ${PS3DEV}/host/ppu/ppu/lib/lv2-psl1ght.o -lpsl1ght -llv2" \
        --disable-ffserver \
        --disable-ffmpeg \
        --disable-ffplay \
        --disable-ffprobe \
        --disable-bzlib \
	--cross-prefix=${PS3DEV}/host/ppu/bin/ppu- \
	--enable-cross-compile \
	--arch=powerpc64 \
	--target-os=none \
	--disable-decoder=twinvq \
	--disable-decoder=snow \
	--disable-decoder=cavs

    make ${PARALLEL}
    make install

fi
