#!/bin/sh

echo >"$2" "//Autogenerated"
echo >>"$2" "#ifdef CONFIG_LIBSPOTIFY_LOAD_RUNTIME"
grep <"$1" SP_LIBEXPORT|grep -v "#" | sed "s/SP_LIBEXPORT(\(.*\))\ \(.*\)(\(.*\));/static \1(*f_\2)(\3);/" >>"$2"
echo >>"$2" "static const char *resolvesym(void *handle) {"
grep <"$1" SP_LIBEXPORT|grep -v "#" | sed "s/SP_LIBEXPORT(\(.*\))\ \(.*\)(\(.*\));/if((f_\2=dlsym(handle,\"\2\"))==NULL) return \"\2\";/"  >>"$2"
echo >>"$2" "return NULL;}"
echo >>"$2" "#else"
grep <"$1" SP_LIBEXPORT|grep -v "#" | sed "s/SP_LIBEXPORT(\(.*\))\ \(.*\)(\(.*\));/#define f_\2 \2/"  >>"$2"
echo >>"$2" "#endif"
