#!/bin/bash


WIISUPPORT=${PWD}/wiisupport

mkdir -p ${WIISUPPORT}

export DEVKITPRO=${WIISUPPORT}/devkitpro
export DEVKITPPC=${DEVKITPRO}/devkitPPC

if ! test -e ${DEVKITPPC} ; then
    mkdir -p ${DEVKITPRO}
    cd ${DEVKITPRO}
    wget http://sunet.dl.sourceforge.net/sourceforge/devkitpro/devkitPPC_r18-i686-linux.tar.bz2
    tar xvf devkitPPC_r18-i686-linux.tar.bz2
fi

### Get and compile libogc


if ! test -e ${DEVKITPRO}/libogc/lib/wii ; then
    mkdir -p ${DEVKITPRO}/libogc-src
    cd ${DEVKITPRO}/libogc-src
    wget http://downloads.sourceforge.net/project/devkitpro/libogc/libogc-src-1.8.0.tar.bz2
    tar xvf libogc-src-1.8.0.tar.bz2
    make wii install
fi

### Get libfat

if ! test -e ${DEVKITPRO}/libfat/lib ; then
    mkdir -p ${DEVKITPRO}/libfat
    cd ${DEVKITPRO}/libfat
    wget http://sunet.dl.sourceforge.net/sourceforge/devkitpro/libfat-ogc-1.0.5.tar.bz2
    tar xvf libfat-ogc-1.0.5.tar.bz2
fi

### Get freetype

if ! test -e ${WIISUPPORT}/freetype-ppc ; then
    cd ${WIISUPPORT}
    wget http://mirrors.zerg.biz/nongnu/freetype/freetype-2.3.9.tar.bz2
    tar xvf freetype-2.3.9.tar.bz2
    cd ${WIISUPPORT}/freetype-2.3.9
    OBJDUMP="${DEVKITPRO}/devkitPPC/bin/powerpc-eabi-objdump" \
	LD="${DEVKITPRO}/devkitPPC/bin/powerpc-eabi-ld" \
	STRIP="${DEVKITPRO}/devkitPPC/bin/powerpc-eabi-strip" \
	RANLIB="${DEVKITPRO}/devkitPPC/bin/powerpc-eabi-ranlib" \
	AR="${DEVKITPRO}/devkitPPC/bin/powerpc-eabi-ar" \
	CFLAGS="-mcpu=750 -O2" \
	CC="${DEVKITPRO}/devkitPPC/bin/powerpc-eabi-gcc" \
	./configure --host=ppc --prefix=${WIISUPPORT}/freetype-ppc \
	--disable-static 

    make && make install
fi

