	"!!ARBfp1.0\n"
	"# cgc version 3.0.0007, build date Jul 22 2010\n"
	"# command line args: -quiet -profile arbfp1\n"
	"# source file: yuv2rgb_2mix_rect.cg\n"
	"#vendor NVIDIA Corporation\n"
	"#version 3.0.0.07\n"
	"#profile arbfp1\n"
	"#program main\n"
	"#semantic main.lum_a : TEXUNIT0\n"
	"#semantic main.Cr_a : TEXUNIT1\n"
	"#semantic main.Cb_a : TEXUNIT2\n"
	"#semantic main.lum_b : TEXUNIT3\n"
	"#semantic main.Cr_b : TEXUNIT4\n"
	"#semantic main.Cb_b : TEXUNIT5\n"
	"#semantic main.ctrl\n"
	"#semantic main.r_vec\n"
	"#semantic main.g_vec\n"
	"#semantic main.b_vec\n"
	"#var float2 uv : $vin.TEX0 : TEX0 : 0 : 1\n"
	"#var samplerRECT lum_a : TEXUNIT0 : texunit 0 : 1 : 1\n"
	"#var samplerRECT Cr_a : TEXUNIT1 : texunit 1 : 2 : 1\n"
	"#var samplerRECT Cb_a : TEXUNIT2 : texunit 2 : 3 : 1\n"
	"#var samplerRECT lum_b : TEXUNIT3 : texunit 3 : 4 : 1\n"
	"#var samplerRECT Cr_b : TEXUNIT4 : texunit 4 : 5 : 1\n"
	"#var samplerRECT Cb_b : TEXUNIT5 : texunit 5 : 6 : 1\n"
	"#var float4 ctrl :  : c[0] : 7 : 1\n"
	"#var float3 r_vec :  : c[1] : 8 : 1\n"
	"#var float3 g_vec :  : c[2] : 9 : 1\n"
	"#var float3 b_vec :  : c[3] : 10 : 1\n"
	"#var float4 main : $vout.COLOR : COL : -1 : 1\n"
	"#const c[4] = 0.5 -0.0625 -0.5 1\n"
	"PARAM c[5] = { program.local[0..3],\n"
	"		{ 0.5, -0.0625, -0.5, 1 } };\n"
	"TEMP R0;\n"
	"TEMP R1;\n"
	"TEMP R2;\n"
	"ADD R0.z, fragment.texcoord[0].y, c[0].w;\n"
	"MUL R1.z, fragment.texcoord[0].x, c[4].x;\n"
	"MUL R1.w, R0.z, c[4].x;\n"
	"TEX R1.x, R1.zwzw, texture[4], RECT;\n"
	"MOV R2.z, R1.x;\n"
	"MOV R0.x, fragment.texcoord[0];\n"
	"MOV R0.y, R0.z;\n"
	"TEX R2.x, R0, texture[3], RECT;\n"
	"TEX R0.x, R1.zwzw, texture[5], RECT;\n"
	"MOV R2.y, R0.x;\n"
	"ADD R0.x, fragment.texcoord[0].y, c[0].z;\n"
	"ADD R0.yzw, R2.xxyz, c[4].xyzz;\n"
	"MOV R1.y, R0.x;\n"
	"MOV R1.x, fragment.texcoord[0];\n"
	"TEX R2.x, R1, texture[0], RECT;\n"
	"MUL R1.y, R0.x, c[4].x;\n"
	"MOV R1.x, R1.z;\n"
	"TEX R0.x, R1, texture[1], RECT;\n"
	"MOV R2.z, R0.x;\n"
	"TEX R1.x, R1, texture[2], RECT;\n"
	"MOV R2.y, R1.x;\n"
	"ADD R1.xyz, R2, c[4].yzzw;\n"
	"MOV R0.x, c[4].w;\n"
	"DP3 R2.x, R0.yzww, c[1];\n"
	"DP3 R2.y, R0.yzww, c[2];\n"
	"DP3 R2.z, R0.yzww, c[3];\n"
	"ADD R0.x, R0, -c[0].y;\n"
	"MUL R0.xyz, R2, R0.x;\n"
	"DP3 R2.x, R1, c[1];\n"
	"DP3 R2.y, R1, c[2];\n"
	"DP3 R2.z, R1, c[3];\n"
	"MAD result.color.xyz, R2, c[0].y, R0;\n"
	"MOV result.color.w, c[0].x;\n"
	"END\n"
	"# 33 instructions, 3 R-regs\n"
