	"!!ARBfp1.0\n"
	"# cgc version 1.4.0001, build date Mar  9 2006 20:56:09\n"
	"# command line args: -quiet -profile arbfp1\n"
	"# source file: yuv2rgb.arbfp1\n"
	"#vendor NVIDIA Corporation\n"
	"#version 1.0.02\n"
	"#profile arbfp1\n"
	"#program main\n"
	"#semantic main.lum : TEXUNIT0\n"
	"#semantic main.Cr : TEXUNIT1\n"
	"#semantic main.Cb : TEXUNIT2\n"
	"#semantic main.ctrl\n"
	"#semantic main.r_vec\n"
	"#semantic main.g_vec\n"
	"#semantic main.b_vec\n"
	"#var half2 uv : $vin.TEX0 : TEX0 : 0 : 1\n"
	"#var sampler2D lum : TEXUNIT0 : texunit 0 : 1 : 1\n"
	"#var sampler2D Cr : TEXUNIT1 : texunit 1 : 2 : 1\n"
	"#var sampler2D Cb : TEXUNIT2 : texunit 2 : 3 : 1\n"
	"#var float4 ctrl :  : c[0] : 4 : 1\n"
	"#var float3 r_vec :  : c[2] : 5 : 1\n"
	"#var float3 g_vec :  : c[3] : 6 : 1\n"
	"#var float3 b_vec :  : c[4] : 7 : 1\n"
	"#var float4 main : $vout.COLOR : COL : -1 : 1\n"
	"#const c[1] = -0.0625 -0.5\n"
	"PARAM c[5] = { program.local[0],\n"
	"		{ -0.0625, -0.5 },\n"
	"		program.local[2..4] };\n"
	"TEMP R0;\n"
	"TEMP R1;\n"
	"MOV R0.z, fragment.texcoord[0].x;\n"
	"ADD R0.w, fragment.texcoord[0].y, c[0].y;\n"
	"TEX R0.x, R0.zwzw, texture[0], 2D;\n"
	"MOV R0.y, R0.x;\n"
	"TEX R0.x, R0.zwzw, texture[1], 2D;\n"
	"TEX R1.x, R0.zwzw, texture[2], 2D;\n"
	"MOV R0.z, R0.x;\n"
	"MOV R0.x, R1;\n"
	"ADD R0.xyz, R0.yxzw, c[1].xyyw;\n"
	"DP3 result.color.x, R0, c[2];\n"
	"DP3 result.color.y, R0, c[3];\n"
	"DP3 result.color.z, R0, c[4];\n"
	"MOV result.color.w, c[0].x;\n"
	"END\n"
	"# 13 instructions, 2 R-regs\n"
