	"!!ARBfp1.0\n"
	"# cgc version 1.4.0001, build date Mar  9 2006 20:56:09\n"
	"# command line args: -quiet -profile arbfp1\n"
	"# source file: yuv2rgb_2mix.arbfp1\n"
	"#vendor NVIDIA Corporation\n"
	"#version 1.0.02\n"
	"#profile arbfp1\n"
	"#program main\n"
	"#semantic main.lum_a : TEXUNIT0\n"
	"#semantic main.Cr_a : TEXUNIT1\n"
	"#semantic main.Cb_a : TEXUNIT2\n"
	"#semantic main.lum_b : TEXUNIT3\n"
	"#semantic main.Cr_b : TEXUNIT4\n"
	"#semantic main.Cb_b : TEXUNIT5\n"
	"#semantic main.ctrl\n"
	"#semantic main.r_vec\n"
	"#semantic main.g_vec\n"
	"#semantic main.b_vec\n"
	"#var half2 uv : $vin.TEX0 : TEX0 : 0 : 1\n"
	"#var sampler2D lum_a : TEXUNIT0 : texunit 0 : 1 : 1\n"
	"#var sampler2D Cr_a : TEXUNIT1 : texunit 1 : 2 : 1\n"
	"#var sampler2D Cb_a : TEXUNIT2 : texunit 2 : 3 : 1\n"
	"#var sampler2D lum_b : TEXUNIT3 : texunit 3 : 4 : 1\n"
	"#var sampler2D Cr_b : TEXUNIT4 : texunit 4 : 5 : 1\n"
	"#var sampler2D Cb_b : TEXUNIT5 : texunit 5 : 6 : 1\n"
	"#var float4 ctrl :  : c[0] : 7 : 1\n"
	"#var float3 r_vec :  : c[2] : 8 : 1\n"
	"#var float3 g_vec :  : c[3] : 9 : 1\n"
	"#var float3 b_vec :  : c[4] : 10 : 1\n"
	"#var float4 main : $vout.COLOR : COL : -1 : 1\n"
	"#const c[1] = -0.0625 -0.5 1\n"
	"PARAM c[5] = { program.local[0],\n"
	"		{ -0.0625, -0.5, 1 },\n"
	"		program.local[2..4] };\n"
	"TEMP R0;\n"
	"TEMP R1;\n"
	"TEMP R2;\n"
	"MOV R1.z, fragment.texcoord[0].x;\n"
	"ADD R1.w, fragment.texcoord[0].y, c[0];\n"
	"TEX R1.x, R1.zwzw, texture[3], 2D;\n"
	"MOV R1.y, R1.x;\n"
	"MOV R0.z, fragment.texcoord[0].x;\n"
	"ADD R0.w, fragment.texcoord[0].y, c[0].z;\n"
	"TEX R0.x, R0.zwzw, texture[0], 2D;\n"
	"MOV R0.y, R0.x;\n"
	"TEX R0.x, R0.zwzw, texture[1], 2D;\n"
	"TEX R1.x, R1.zwzw, texture[4], 2D;\n"
	"TEX R2.x, R1.zwzw, texture[5], 2D;\n"
	"MOV R1.z, R1.x;\n"
	"MOV R1.x, R2;\n"
	"ADD R2.xyz, R1.yxzw, c[1].xyyw;\n"
	"TEX R1.x, R0.zwzw, texture[2], 2D;\n"
	"MOV R0.z, R0.x;\n"
	"MOV R0.x, R1;\n"
	"MOV R0.w, c[1].z;\n"
	"DP3 R1.x, R2, c[2];\n"
	"DP3 R1.y, R2, c[3];\n"
	"DP3 R1.z, R2, c[4];\n"
	"ADD R0.xyz, R0.yxzw, c[1].xyyw;\n"
	"ADD R0.w, -c[0].y, R0;\n"
	"MUL R1.xyz, R1, R0.w;\n"
	"DP3 R2.x, R0, c[2];\n"
	"DP3 R2.y, R0, c[3];\n"
	"DP3 R2.z, R0, c[4];\n"
	"MAD result.color.xyz, R2, c[0].y, R1;\n"
	"MOV result.color.w, c[0].x;\n"
	"END\n"
	"# 29 instructions, 3 R-regs\n"
